name: Send a telegram message when new hot subreddit
on:
  reddit:
    url: https://reddit.com/r/news/
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{ on.reddit.outputs.title }}
          contentSnippet: ${{ on.reddit.outputs.title }}
          link: ${{ on.reddit.outputs.title }}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
